name: Issues content
on: issues
jobs:
  output-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub Context
        run: echo "${{ toJson(github) }}"
